# -*- mode: ruby -*-
# vi: set ft=ruby :

$init = <<SCRIPT
#!/bin/bash

export PATH=$PATH:/usr/local/bin

apt-get update
apt-get -y install nginx
cat <<EOF > /etc/nginx/conf.d/test.conf
server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.nginx-debian.html;
    location / {
        try_files $uri $uri/ =404;
    }
}
EOF
systemctl restart nginx
echo "You can reach nginx at http://$(ip a | grep -w inet | grep -v 127.0.0.1 | grep -v 10.0.2.15 | awk '{print $2}' | cut -d/ -f1)"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = true
  config.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"
  
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"

    # Set name in Virtualbox
    vb.name = "vagrant"
  end

  # Prep the box to use our ssh keys
  config.vm.provision "shell", inline: $init

  # Informational message
  config.vm.post_up_message = "To ssh into the VM, simply type 'vagrant ssh'"
end